/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  Auth: {
    Cognito: {
      userPoolClientId: "e34tkhfoepujgre0imt7gikpt",
      userPoolId: "us-east-1_X8yePKlex",
      loginWith: {
        // Optional
        // oauth: {
        //   domain: "ncbp-user-pool.auth.us-east-1.amazoncognito.com",
        //   scope: ["phone", "email", "openid", "profile"],
        //   redirectSignIn:
        //     "http://frontend-lb-731922503.us-east-2.elb.amazonaws.com/",
        //   redirectSignOut:
        //     "http://frontend-lb-731922503.us-east-2.elb.amazonaws.com/",
        //   responseType: "code",
        // },
        username: false,
        email: true, // Optional
        phone: false, // Optional
      },
    },
  },
};

export default awsmobile;
